export const enum blockType {
  Accordion = 'Accordion',
  BenefitsBlock = 'BenefitsBlock',
  ComparisonTable_with_images = 'ComparisonTable with images',
  ComparisonTable_with_images_and_hidden_rows = 'ComparisonTable with images and hidden rows',
  ComparisonTable_with_images_and_colored_first_column = 'ComparisonTable with images and colored first column',
  ComparisonTable_with_icons = 'ComparisonTable with icons',
  ComparisonTable_with_icons_and_two_cols = 'ComparisonTable with icons and two cols',
  CreditCalculator = 'CreditCalculator',
  ExchangeRateTile_default = 'ExchangeRateTile default',
  Footer = 'Footer',
  Gallery_default = 'Gallery default',
  Gallery_text_and_button = 'Gallery text and button',
  Gallery_list_and_button = 'Gallery list and button',
  Gallery_text_and_no_button = 'Gallery text and no button',
  Gallery_only_title = 'Gallery only title',
  Gallery_mobile = 'Gallery mobile',
  Header_default = 'Header default',
  Header_transparent = 'Header transparent',
  Headline_default = 'Headline default',
  Headline_left_white = 'Headline left white',
  Headline_right_transparent = 'Headline right transparent',
  LikeControl = 'LikeControl',
  LinkDocs_two_columns_default = 'LinkDocs two columns (default)',
  LinkDocs_one_column = 'LinkDocs one column',
  LinkDocs_another_icon = 'LinkDocs another icon',
  LinkDocs_no_icon_and_title = 'LinkDocs no icon and title',
  MiniGallery_default = 'MiniGallery default',
  MiniGallery_only_title = 'MiniGallery only title',
  MobileAppTile_default = 'MobileAppTile default',
  Navigation = 'Navigation',
  Placeholder = 'Placeholder',
  PictureText_default = 'PictureText default',
  ProductBlock_default = 'ProductBlock default',
  ProductBlock_secondary = 'ProductBlock secondary',
  ProductBlock_with_items = 'ProductBlock with items',
  ProductGallery = 'ProductGallery',
  ProductTile_credit = 'ProductTile credit',
  ProductTile_pension = 'ProductTile pension',
  ProductTile_credit_card = 'ProductTile credit-card',
  ProductTile_pension_credit = 'ProductTile pension-credit',
  PromoTile_default = 'PromoTile default',
  StepsBlock = 'StepsBlock',
  TariffsTable_default = 'TariffsTable default',
  TariffsTable_1_column = 'TariffsTable 1 column',
  TariffsTable_2_columns = 'TariffsTable 2 columns',
  TariffsTable_3_columns = 'TariffsTable 3 columns',
  TextBlock = 'TextBlock',
  Tile_credit = 'Tile credit',
  Tile_mortgage = 'Tile mortgage',
  Tile_credit_card = 'Tile credit-card',
  Tile_premium = 'Tile premium',
  Tile_ecosystem = 'Tile ecosystem',
}

export const getBlock = () => cy.get('div[data-theme]:first > *');

export const activeSearchBar = () => cy.get('#search-bar-input').should('exist').type('тест');

export const galleryScrollRight = () =>
  cy.get("[aria-label='Пролистать вправо']").should('exist').click();
