name: e2e-visual-regression

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test

      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run cosmos:export
          start: npx -y http-server ./docs/ -d false -g
          wait-on: 'http://localhost:8080/'
          browser: chrome
          command: npm run e2e:test
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
          retention-days: 1
