name: e2e-update-snapshots

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - run: npm ci
      - run: npm test

      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run cosmos:export
          start: npx -y http-server ./docs/ -d false -g
          wait-on: 'http://localhost:8080/'
          browser: chrome
          command: npm run e2e:base
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[skip ci] Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots
          retention-days: 1
