name: e2e-visual-regression

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress.io
        uses: cypress-io/github-action@v4.1.1
        with:
          build: npm run cosmos:export
          start: npx -y http-server ./docs/ -d false -g
          wait-on: 'http://localhost:8080/'
          browser: chrome
          command: npm run e2e:test
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots/diff
          retention-days: 1
