name: main

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: jq -s add ./package.json ./.public.package.json > ./temp.package.json && mv ./temp.package.json ./package.json
      - run: npm ci && npm install react react-dom --no-save
      - run: npm run build
      - run: npm test
        env:
          CI: true
      - run: tar -cvf docs.tar ./docs
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          retention-days: 1
          path: docs.tar
      - run: tar -cvf dist.tar ./lib ./dist ./bundle ./fonts ./mobile ./cosmos-static/icons
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          retention-days: 1
          path: dist.tar

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - run: tar -xvf dist.tar
      - run: jq -s add ./package.json ./.public.package.json > ./temp.package.json && mv ./temp.package.json ./package.json
      - run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access=public --ignore-scripts || exit 0
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  lighthouse:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: docs
      - run: tar -xvf docs.tar
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true

  lighthouse-mobile:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: docs
      - run: tar -xvf docs.tar
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc.mobile.json'
          uploadArtifacts: true
